spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      uery-timeout: 3
  redis:

    database: 0  #Redis数据库索引(默认为0)
#    host: 127.0.0.1 #Redis服务器地址
#    #Redis服务器连接端口
#    port: 6379
    #Redis服务器连接密码
    password:
    cluster:
        nodes: 192.168.249.1:6379,192.168.249.1:6380,192.168.249.1:6381,192.168.249.1:6382,192.168.249.1:6383,192.168.249.1:6384
#        nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
    client-type: jedis
    jedis:
      pool:
        max-active: 1000  #连接池最大连接数(只用负数值表示没有限制)
        max-wait: -1   #连接池最大阻塞等待时间(只用负数值表示没有限制)
        max-idle: 10   #连接池中的最大空闲连接
        min-idle: 2    #连接池中的最小空闲连接
    #连接超时时间(毫秒)
    timeout: 60

  session:
    store-type: redis
    timeout: 100 #30分钟 30x60


