spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0  #Redis数据库索引(默认为0)
    host: 127.0.0.1 #Redis服务器地址
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码
    password:
    client-type: jedis
    jedis:
      pool:
        max-active: 1000  #连接池最大连接数(只用负数值表示没有限制)
        max-wait: -1   #连接池最大阻塞等待时间(只用负数值表示没有限制)
        max-idle: 10   #连接池中的最大空闲连接
        min-idle: 2    #连接池中的最小空闲连接
    #连接超时时间(毫秒)
    timeout: 0

#    druid:
#      aop-patterns: com.atguigu.admin.*  #springbean监控
#      filters: stat,wall,slf4j  #所有开启的功能
#
#      stat-view-servlet:  #监控页配置
#        enabled: true
#        login-username: admin
#        login-password: admin
#        resetEnable: false
#
#      web-stat-filter:  #web监控
#        enabled: true
#        urlPattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#
#
#      filter:
#        stat: #sql监控
#          slow-sql-millis: 1000
#          logSlowSql: true
#          enabled: true
#        wall: #防火墙
#          enabled: true
#          config:
#            drop-table-allow: false
#
#




  #    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3
#  boot:
#    admin:
#      client:
#        url: http://localhost:8888
#        instance:
#          prefer-ip: true  #使用ip注册进来
#  application:
#    name: boot-05-web-admin
#



# 配置mybatis规则、使用MyBatisPlus则此项配置无效
#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:  # 指定mybatis全局配置文件中的相关配置项
#    map-underscore-to-camel-case: true


# management 是所有actuator的配置
# management.endpoint.端点名.xxxx  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true  #默认开启所有监控端点  true
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点

  endpoint:   #对某个端点的具体配置
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@



